Develop a program to implement Naive Bayes classifier model and analyze the model using confusion matrix

In [1]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB

In [6]:
iris_df = pd.read_csv('Iris_data_sample.csv',header =None)
iris_df.info()
iris_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151 entries, 0 to 150
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       150 non-null    float64
 1   1       151 non-null    object 
 2   2       150 non-null    object 
 3   3       150 non-null    object 
 4   4       151 non-null    object 
 5   5       150 non-null    object 
dtypes: float64(1), object(5)
memory usage: 7.2+ KB


0              1             2              3             4  \
0      NaN  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm   
1      1.0            5.1           3.5            1.4           0.2   
2      2.0            4.9           NaN            1.4           0.2   
3      3.0            4.7           3.2            1.3           0.2   
4      4.0             ??           3.1            1.5           0.2   
..     ...            ...           ...            ...           ...   
146  146.0            6.7             3            5.2           2.3   
147  147.0            6.3           2.5              5           1.9   
148  148.0            6.5             3            5.2             2   
149  149.0            6.2           3.4            5.4           2.3   
150  150.0            5.9             3            5.1           1.8   

                  5  
0           Species  
1       Iris-setosa  
2               NaN  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  
150  Iris-virginica  

[151 rows x 6 columns]

In [8]:
iris_df = iris_df.replace(to_replace =['??','###'],value =None) 
iris_df.dropna(axis = 0, how='any',inplace = True)
iris_df.info()
iris_df.iloc[:,5].value_counts()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 148 entries, 1 to 150
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       148 non-null    float64
 1   1       148 non-null    object 
 2   2       148 non-null    object 
 3   3       148 non-null    object 
 4   4       148 non-null    object 
 5   5       148 non-null    object 
dtypes: float64(1), object(5)
memory usage: 8.1+ KB


Iris-versicolor    50
Iris-virginica     50
Iris-setosa        48
Name: 5, dtype: int64

In [9]:
iris_df

0    1    2    3    4               5
1      1.0  5.1  3.5  1.4  0.2     Iris-setosa
3      3.0  4.7  3.2  1.3  0.2     Iris-setosa
4      4.0  4.7  3.1  1.5  0.2     Iris-setosa
5      5.0    5  3.6  1.5  0.2     Iris-setosa
7      7.0  4.6  3.4  1.4  0.3     Iris-setosa
..     ...  ...  ...  ...  ...             ...
146  146.0  6.7    3  5.2  2.3  Iris-virginica
147  147.0  6.3  2.5    5  1.9  Iris-virginica
148  148.0  6.5    3  5.2    2  Iris-virginica
149  149.0  6.2  3.4  5.4  2.3  Iris-virginica
150  150.0  5.9    3  5.1  1.8  Iris-virginica

[148 rows x 6 columns]

In [10]:
X_features = iris_df.iloc[:,1:5]
X_features

1    2    3    4
1    5.1  3.5  1.4  0.2
3    4.7  3.2  1.3  0.2
4    4.7  3.1  1.5  0.2
5      5  3.6  1.5  0.2
7    4.6  3.4  1.4  0.3
..   ...  ...  ...  ...
146  6.7    3  5.2  2.3
147  6.3  2.5    5  1.9
148  6.5    3  5.2    2
149  6.2  3.4  5.4  2.3
150  5.9    3  5.1  1.8

[148 rows x 4 columns]

In [11]:
Y_features = iris_df.iloc[:,5]
Y_features

1         Iris-setosa
3         Iris-setosa
4         Iris-setosa
5         Iris-setosa
7         Iris-setosa
            ...      
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
150    Iris-virginica
Name: 5, Length: 148, dtype: object

In [14]:
model = GaussianNB()
model.fit(X_features, Y_features)

GaussianNB()

In [15]:
expected = Y_features
predicted = model.predict(X_features)
predicted

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
     

In [16]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(expected, predicted))

Accuracy: 0.9594594594594594


In [17]:
print(metrics.confusion_matrix(expected,predicted))

[[48  0  0]
 [ 0 47  3]
 [ 0  3 47]]


In [19]:
#Precision = TP/(TP + FP),
#Recall = TP/(TP+FN),
#F1 Score = 2*(Recall * Precision) / (Recall + Precision),
#the number of actual occurrences of the class in the specified dataset

In [18]:
print(metrics.classification_report(expected, predicted))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        48
Iris-versicolor       0.94      0.94      0.94        50
 Iris-virginica       0.94      0.94      0.94        50

       accuracy                           0.96       148
      macro avg       0.96      0.96      0.96       148
   weighted avg       0.96      0.96      0.96       148

